name: Continuous Deployment

on:
  push:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options: [staging, production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'staging' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          npm ci
          cd frontend && npm ci
          cd ../backend && npm ci
          cd ../ai-services && pip install -r requirements.txt
          
      - name: Build applications
        run: |
          cd frontend && npm run build
          cd ../backend && npm run build
          
      - name: Deploy to staging
        if: github.event.inputs.environment == 'staging' || github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to staging environment..."
          # Add actual deployment commands here
          
      - name: Health check
        run: |
          echo "Running health checks..."
          curl -f https://staging.investorshiksha.com/health || exit 1
